### PR TITLE
Make the script POSIX compliant so it works with dash (Fixes #977)

### LINKED ISSUE #977: Boulder integration test: unexpected operator
https://travis-ci.org/letsencrypt/letsencrypt/letsencrypt/jobs/85367670#L1045

```
+uname
+[ Linux == Darwin ]
./tests/boulder-integration.sh: 17: [: Linux: unexpected operator
```

Interestingly, despite `-x -e`, scripts proceeds to a next step.

### PR DESCRIPTION
**Pull request by ddworken**
Looks like the problem was introduced [here](https://github.com/letsencrypt/letsencrypt/commit/c9e28309ed2d3efb3c2c21301f88796fe87169ab) likely due to @BKreisel having /usr/bin/sh set to bash (which this works on) rather than dash (which this fails on). 

So the fix is pretty simple, just switch to ```=``` instead of ```==``` so as to make the script POSIX compliant to fix #977.

### CODE REVIEW

**Comment by ddworken** [comment]
[No more error](https://travis-ci.org/letsencrypt/letsencrypt/jobs/85645573#L1074)

**Comment by bmw** [comment]
LGTM. Thanks @ddworken.

File: tests/boulder-integration.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@ export PATH="/usr/sbin:$PATH"  # /usr/sbin/nginx
 export GOPATH="${GOPATH:-/tmp/go}"
 export PATH="$GOPATH/bin:$PATH"
 
-if [ `uname`  == 'Darwin' ]; then
+if [ `uname` = "Darwin" ];then
```
Comment (kuba) [inline tests/boulder-integration.sh]: you removed whitespace :(

Comment (ddworken) [inline tests/boulder-integration.sh]: Sorry about that. Are we following a specific style guide for shell code? I looked up the [Google Style Guide for shell scripts](http://google.github.io/styleguide/shell.xml) and I can tell we aren't following that since it says to always use bash (though it does agree with you that it should be ```; then```). Just grepping for ```;then``` and ```; then``` on my system, I see plenty of both (in packages provided by Ubuntu).
